"""Altered user mode used server default for the timezone

Revision ID: b7715a6f282f
Revises: 5fbc2193e402
Create Date: 2026-09-29 13:06:20.053478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7715a6f282f'
down_revision: Union[str, Sequence[str], None] = '5fbc2193e402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'timezone',
               existing_type=mysql.VARCHAR(length=50),
               server_default='UTC',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=True)
    op.alter_column('users', 'timezone',
               existing_type=mysql.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
